name: test-workflow
on:
    [workflow_dispatch, push]
jobs:
    test1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@4.0.0
            - name: Run tests
              run: ls | dir
