name: Python application test
on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check Python version
      run: python3 --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CherryPy server in the background
      run: |
        python3 main.py &
        sleep 5  # Give the server some time to start

    - name: Run tests
      run: python3 -c "import requests; response = requests.get('http://localhost:8080'); assert response.status_code == 200; assert response.text == 'Hello World!'"
