name: test-workflow
on:
    [workflow_dispatch]
jobs:
    test1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Notify on Teams
              env:
                  WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}
              run: |
                curl -H "Content-Type: application/json" -d @test.json $WEBHOOK_URL
            - name: Setup Python
              uses: actions/setup-python@v5.0.0
            - name: Install Dependencies
              run: pip install -r requirements.txt
            
