name: test-workflow
on:
    [workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            #- name: Notify on Teams
            #  env:
            #      WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}
            #  run: |
            #    curl -H "Content-Type: application/json" -d @test.json $WEBHOOK_URL
            - name: Install Dependencies
              run: pip install -r requirements.txt
            - name: Run Server
              run: python main.py
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Send a request
              run: curl localhost:8080
    
            
