name: test-workflow
on:
    [workflow_dispatch, push]
jobs:
    test1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run tests
              run: |
                echo "Running tests"
                echo "Tests passed"

    test2:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              if: github.event_name == 'push'
              run: echo "Hello"
